env:
  node: true
  es2021: true
plugins:
  - import
  - unused-imports
extends:
  - eslint:recommended
  - plugin:import/errors
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-unused-vars: off
  import/order:
    - error
    - groups:
      - builtin
      - external
      - internal
      newlines-between: always
      alphabetize:
        order: asc
  unused-imports/no-unused-imports: error
  unused-imports/no-unused-vars:
    - warn
    - vars: all
      varsIgnorePattern: ^_
      args: after-used
      argsIgnorePattern: ^_
  indent:
  - 2
  - 4
  quotes:
  - 2
  - single
  - allowTemplateLiterals: true
  semi:
  - 2
  - always
  keyword-spacing:
  - 2
  - before: true
    after: true
  eqeqeq:
  - 2
  - always
  comma-spacing:
  - 2
  - before: false
    after: true
  brace-style:
  - 2
  - 1tbs
  curly:
  - 2
  - all
  operator-linebreak:
  - 2
  - before
  camelcase:
  - 2
  - properties: always
  comma-dangle:
  - 2
  - always-multiline
  dot-location:
  - 2
  - property
  eol-last:
  - 2
  - always
  func-call-spacing:
  - 2
  - never
  new-parens:
  - 2
  - always
  no-duplicate-imports:
  - 2
  - includeExports: true
  no-extend-native: error
  object-curly-spacing:
  - 2
  - always
  template-curly-spacing:
  - 2
  - never
  arrow-spacing: error
  space-before-function-paren:
  - 2
  - anonymous: never
    named: never
    asyncArrow: always
  key-spacing:
  - 2
  - beforeColon: false
    afterColon: true
  no-empty:
  - 2
  - allowEmptyCatch: true
